### ISSUE TITLE
Issues with ASTContext.GenerateEnumFromMacros()

### ISSUE THREAD

**Issue by TheLastRar** [mono/CppSharp#1047] opened 2018-01-13 16:56 UTC
##### Brief Description

GenerateEnumFromMacros does not populate Namespace for the new enum, this causes a crash later on after Preprocess()

GenerateEnumFromMacros does not evaluate (or otherwise copy) the expression/value of the define, giving all enum entries a value of zero.

This one is a bit of a nitpick, but comments relating to the defines aren't copied into the C# enum, not sure how feasible it would be to resolve that.

OS: Windows

Target: MSVC/GCC/Clang

**Comment by tritao** [comment] 2018-01-14 00:49
Want to try to send a fix?

**Comment by TheLastRar** [comment] 2018-01-14 15:00
Maybe.

I'm not sure how to fix the second issue, do you have something that would evaluate expressions already?

I'm currently working around this issue by using the Microsoft.CodeAnalysis.CSharp.Scripting package to evaluate them myself.

**Comment by tritao** [comment] 2018-01-14 20:08
I took a quick look around and found this expression evaluator: https://github.com/codingseb/ExpressionEvaluator

I wonder if you could use it instead of us taking a dependency on Roslyn, it seems pretty self-contained, just a single file so should be easy to embed in CppSharp.

**Comment by TheLastRar** [comment] 2018-01-14 22:42
Sure, seems to do the job.

The file has an additional dependency on "Microsoft.CSharp", although I'm not sure where the appropriate place to add that dependency is, given that the VS solution files are auto generated.

How would you like the file included? I just put the file in "src\Generator\Utils" without any changes

**Comment by TheLastRar** [comment] 2018-01-14 23:39
MacroDefinition don't have a track any comments made, so I've decided to leave the issue of copying comments as is.

**Comment by tritao** [comment] 2018-01-14 23:52
The issue is that  Clang attaches documentation comments to AST declarations, and macro definitions are not considered declarations since they are declared in the Lexer module.

We could probably store the raw text for the entire `#define` line and extract the comment from that with a regex.

If you want to do that, then you need to slightly extend this code to get the code text for the entire line: https://github.com/mono/CppSharp/blob/master/src/CppParser/Parser.cpp#L3437

**Comment by tritao** [comment] 2018-01-14 23:54
It might be enough to use a variation of the code in the first case of the switch:

```
        std::string Text;
        GetDeclText(PPEntity->getSourceRange(), Text);
```

**Comment by TheLastRar** [comment] 2018-01-16 18:32
``GetDeclText(PPEntity->getSourceRange(), Text)`` doesn't return the whole line , it omits the #define and comments at the end line.

**Comment by tritao** [comment] 2018-01-16 18:50
You need the range for the whole line, here's what you can use instead:

https://clang.llvm.org/doxygen/classclang_1_1SourceManager.html#a88ecde393b8281f7c0be5afdd0213624

Probably something like:

```
bool Invalid;
const char* Buf = SM->getCharacterData(PPEntity->getSourceRange().getBegin(), &Invalid);
if (!Invalid)
    auto Text = std::string(Buf, strtok(Buf, '\n'))
```

**Comment by TheLastRar** [comment] 2018-02-04 14:04
The nuget package for 0.8.18 doesn't appear to contain the changes added in https://github.com/mono/CppSharp/pull/1048 despite this being noted in the changelog.

**Comment by ddobrev** [comment] 2018-02-04 14:07
@tritao 's just merged it as a single commit, https://github.com/mono/CppSharp/commit/430bbdb2576ee044a6af0006a10f8b57b67fadcb, but it's in.

**Comment by TheLastRar** [comment] 2018-02-04 14:40
On further inspection, CppSharp.Generator.dll has the same hash in both 0.8.18 and 0.8.17 nuget packages.

**Comment by ddobrev** [comment] 2018-02-04 15:18
@TheLastRar there's a new release, please try it.

**Comment by TheLastRar** [comment] 2018-02-04 15:51
New release works, thanks

**Comment by ddobrev** [comment] 2020-06-20 22:06
Closing as the reporter's confirmed it works now.

**Closed by ddobrev** 2020-06-20 22:06 UTC
