### ISSUE TITLE
Two types with same name in hierarchical namespaces.

### ISSUE THREAD

**Issue by jamesford42** [mono/CppSharp#740] opened 2017-01-29 00:19 UTC
I have two C++ enums with the same type name, one in a child namespace of the other.

eg.
```
namespace MyLibrary
{
    enum ErrorCode : int
    {
        // All error codes...
    };

    namespace Network
    {
        enum ErrorCode : int
        {
            // only the error codes having to do with networking
        };
    }
}
```

This is valid code in both C++ and C#. However CppSharp seems to choke with a "error: redefinition of 'ErrorCode'".

**Comment by genuinelucifer** [comment] 2017-02-17 17:23
I can't seem to find any error here.. I used exactly the code you gave above and it successfully generates the following C# Code:
```
namespace MyLibrary
    {
        public enum ErrorCode
        {
        }

        namespace Network
        {
            public enum ErrorCode
            {
            }
        }
    }
```
Also, I tried adding 2 symbols to both the enums and it still got around without any error!

**Comment by ddobrev** [comment] 2017-02-17 17:30
@genuinelucifer thank you, please move on.
@jamesford42 I am afraid we cannot reproduce this one. I have to ask you to provide us with further details, such as the options you use, or, if feasible, give us a way to check your real code (if it's open source as MonoGame is). Otherwise we'll be forced to close this issue.

**Comment by jamesford42** [comment] 2017-02-17 20:06
The actual enums were defined in separate .h files that were included separately, while using the UnityBuild option.

**Comment by ddobrev** [comment] 2017-02-17 20:08
@genuinelucifer when done with your current task, could you please check this one again with the new information?

**Comment by genuinelucifer** [comment] 2017-03-17 11:20
Well, I donno about `UnityBuild` option. But I tried putting the following in AnotherUnit.h:
```C++
namespace MyLibrary
{
    enum ErrorCode : int
    {
        // All error codes...
    };
}
```
and the following in CSharp.h:
```
namespace MyLibrary
{
    namespace Network
    {
        enum ErrorCode : int
        {
            // only the error codes having to do with networking
        };
    }
}
```
Also, `CSharp.h` includes `AnotherUnit.h` . After generating, I got the following code in `CSharp.cs`:

```C#
   namespace MyLibrary
    {
        public enum ErrorCode
        {
        }
    }

/* Some other code */

    namespace MyLibrary
    {
        namespace Network
        {
            public enum ErrorCode
            {
            }
        }
    }
```
.
I think it's pretty okay.. Seeing as how those two pieces were defined separately anyways...

**Comment by ddobrev** [comment] 2017-03-17 12:50
@jamesford42 I am afraid we have been unable to reproduce this issue without a sample. If you would be willing to provide one, please reopen.

**Closed by ddobrev** 2017-03-17 12:50 UTC
