### ISSUE TITLE
Build crash with GCC 5+

### ISSUE THREAD

**Issue by lefta** [mono/CppSharp#572] opened 2015-10-04 20:00 UTC
Hello,
Building with GCC 5+, build crashes with memory corruption. Both LLVM/Clang and CppSharp must be built with GCC 4.9 to go to the end of the build. GCC 5 was not tested, 5.1 failed on Vtables and 5.2 on TypesGen.

GCC 5 made (and still makes, if I'm not wrong) heavy, ABI incompatible changes, so I don't wait for a quick fix, so I would recommend to add a warning to the guide in a first time.

Thanks for the work.

**Comment by tritao** [comment] 2015-10-04 22:38
Thanks for trying to compile with GCC 5, will try to add that configuration to our CI build.

**Comment by tritao** [comment] 2017-09-01 17:10
Duplicate of https://github.com/mono/CppSharp/issues/726

**Closed by tritao** 2017-09-01 17:10 UTC
