### ISSUE TITLE
Generating wrappers for a C++ library for Android 

### ISSUE THREAD

**Issue by birsoyo** [mono/CppSharp#1252] opened 2019-10-04 18:33 UTC
Hi all,

I am trying to generate C# wrappers for a C++ project to be used by Windows/iOS/Android in a xamarin application. Although my prototype works for windows, I am having trouble to generate android bindings. Any input what I am doing wrong is appreciated.

I am working on Windows with android ndk r20 using CppSharp v0.10.1 through nuget.

The current error I am getting is, 
```
C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\bits/pthread_types.h(36,3): error: unknown type name 'uint32_t'
<path>\sysroot\usr\include\bits/pthread_types.h(40,3): error: unknown type name 'int32_t'
[snip]
<path>\sysroot\usr\include\sys/types.h(48,9): error: unknown type name 'uint32_t'
[snip]
```
It looks like it is having trouble finding the proper "stdint.h". It feels like `include_next` is not working or something related to order of my includes or I am missing some preprocessor macro defines.

I think, this is the section of my CppSharp script that is relevant.

```
      const string android_ndk_path = @"C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle";
      const int androidNdkApiLevel = 23;

      var triple = "aarch64-linux-android";
      driver.Options.OutputDir = "generated-android";
      //driver.ParserOptions.NoBuiltinIncludes = true;
      //driver.ParserOptions.NoStandardIncludes = true;
      driver.ParserOptions.TargetTriple = triple;

      var toolchainsPath = Path.Combine(android_ndk_path, "toolchains", "llvm", "prebuilt", "windows-x86_64");
      driver.ParserOptions.AddSystemIncludeDirs(Path.Combine(toolchainsPath, "sysroot", "usr", "local", "include"));
      
      //** Changing the location of this include changes the errors I am getting.
      driver.ParserOptions.AddSystemIncludeDirs(Path.Combine(toolchainsPath, "sysroot", "usr", "include", "c++", "v1"));
      //**

      driver.ParserOptions.AddSystemIncludeDirs(Path.Combine(toolchainsPath, "lib64", "clang", "8.0.7", "include"));
      driver.ParserOptions.AddSystemIncludeDirs(Path.Combine(toolchainsPath, "sysroot", "usr", "include", triple));
      driver.ParserOptions.AddSystemIncludeDirs(Path.Combine(toolchainsPath, "sysroot", "include"));
      driver.ParserOptions.AddSystemIncludeDirs(Path.Combine(toolchainsPath, "sysroot", "usr", "include"));

      driver.ParserOptions.AddDefines($"__ANDROID_API__={androidNdkApiLevel}");
```
Thanks.

**Comment by ddobrev** [comment] 2019-10-04 18:42
Does it make any difference if you uncomment the two settings?
Usually such errors are caused by include directories. If you're certain `uint32_t` is defined in `stdint.h`, please ensure the containing directory is added to your system include directories.

**Comment by birsoyo** [comment] 2019-10-04 19:33
Setting `NoBuiltinIncludes` or `NoStandardIncludes` to true or false do not seem to make difference.

I am pretty sure "stdint.h" is the provider of these "(u)< intergral >_t" types.

There are 6 different "stdint.h" files in the ndk.

They are
1. `toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1`
2. `toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/8.0.7/include`
3. `toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include`
4. `sysroot/usr/include`
5. `toolchains/renderscipt/prebuilt/windows-x86_64/clang-include`
6. `sources/cxx-stl/llvm-libc++/include`

I have, in order, 1, 2, 3 in the path in my CppSharp script. I don't have 4, 5, 6 in the path.
As far as I can tell, the item 3 is the final one that has the defines...

1. `<path>/c++/v1/stdint.h` does some stuff and does a `include_next <stdint.h>`
2. `<path>/clang/8.0.7/include/stdint.h` does some stuff and either defines the types OR does a `include_next <stdint.h>` 
3. `sysroot/usr/include/stdint.h` finally just defines the types.

This is the output of android clang++ output for what it is doing...

```
> .\aarch64-linux-android23-clang++.cmd -E - -v

Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: aarch64-unknown-linux-android23
Thread model: posix
InstalledDir: C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin
Found candidate GCC installation: C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/aarch64-linux-android\4.9.x
Selected GCC installation: C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib/gcc/aarch64-linux-android/4.9.x
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1, version unknown
 "C:\\Users\\obirsoy\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple aarch64-unknown-linux-android23 -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -pic-is-pie -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -mllvm -aarch64-fix-cortex-a53-835769=1 -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -v -resource-dir "C:\\Users\\obirsoy\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\8.0.7" -internal-isystem "C:\\Users\\obirsoy\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin/../sysroot/usr/local/include" -internal-isystem "C:\\Users\\obirsoy\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\8.0.7\\include" -internal-externc-isystem "C:\\Users\\obirsoy\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin/../sysroot/usr/include/aarch64-linux-android" -internal-externc-isystem "C:\\Users\\obirsoy\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin/../sysroot/include" -internal-externc-isystem "C:\\Users\\obirsoy\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin/../sysroot/usr/include" -fdebug-compilation-dir "C:\\Users\\obirsoy\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin" -ferror-limit 19 -fmessage-length 190 -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -o - -x c -
clang -cc1 version 8.0.7 based upon LLVM 8.0.7svn default target x86_64-w64-windows-gnu
ignoring nonexistent directory "C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin/../sysroot/include"
#include "..." search starts here:
#include <...> search starts here:
 C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin/../sysroot/usr/local/include
 C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\8.0.7\include
 C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin/../sysroot/usr/include/aarch64-linux-android
 C:\Users\obirsoy\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin/../sysroot/usr/include
End of search list.
```
Note that there is no `c++/v1` path on the list. But if I don't include `c++/v1` path, I fail with `include <string>` or `include <vector>` much earlier than my original post.

**Comment by tritao** [comment] 2019-12-24 10:20
Hope you've figured it out and got the manual setup to work.

Long-term I think the proper way to go would be hooking into Clang Android toolchain lookup code or write a managed toolchain driver for Android that knows how to set it up automatically.

Please let us know if you'd be willing to sponsor that feature and we could add it to CppSharp, otherwise closing this for now.

**Closed** 2019-12-24 10:22 UTC

**Comment by ryancheung** [comment] 2020-06-09 09:25
So CppSharp does not support android or ios at the moment?

**Comment by tritao** [comment] 2020-06-09 09:42
@ryancheung It supports all targets supported by LLVM/Clang.

You just need to setup the driver manually as explained above, we have some plans to make the setup automatic in the future, but might take some time until we get to it.

**Comment by ryancheung** [comment] 2020-06-09 09:51
@tritao Thanks for reply. I just hadn't found any docs for mobile platforms.
