### ISSUE TITLE
Confused - how do I use this thing?

### ISSUE THREAD

**Issue by kentcb** [mono/CppSharp#910] opened 2017-08-09 05:10 UTC
Forgive me - I'm new to CppSharp and that's certainly going to be a factor here, but I'm super confused about how I'm supposed to use this thing. I'm trying to generate x86 linux bindings from a Windows machine.

Here are some of the things that have confused me so far:

* the home page tells me I can download binaries from GitHub, but the releases there appear to be source only
* the command line tool appears to only be available via NuGet, but in order to use it I have to download the package and copy the EXE alongside the DLLs
* cloning the source gives me no project or solution file, so it's not exactly easy to just get going in VS
* the [Getting Started](https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md) doc talks about setting up CLANG, which I did, but couldn't figure out how to make use of it due to the above
* the command line tool's options suggest that it's possible to generate x86 linux bindings from a Windows machine by passing in `-p` and `-a`. However, whenever I attempt to run the tool, it just spits out the usage info without telling me what I did wrong
* following the [Generating Bindings](https://github.com/mono/CppSharp/blob/master/docs/GeneratingBindings.md) docs, I can't find any equivalent to the console tool's `-p` and `-a` parameters. That is, some options I can set in `Setup` to do the equivalent
* further to this, running my project just results in `BadImageFormatException`, regardless of whether I point the driver at linux or Windows binaries (or none at all!)

I guess I'm just really confused and would like some pointers in the right direction.

fwiw, the `BadImageFormatException` stack trace is:
```
System.BadImageFormatException occurred
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=CppSharp.Parser.CSharp
  StackTrace:
   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr instance)
   at CppSharp.Parser.CppParserOptions..ctor()
   at CppSharp.Parser.ParserOptions..ctor()
   at CppSharp.Driver..ctor(DriverOptions options)
   at CppSharp.ConsoleDriver.Run(ILibrary library)
   at CppBindingGenerator.Program.Main(String[] args) in C:\Users\Kent\documents\visual studio 2017\Projects\Xxx\CppBindingGenerator\Program.cs:line 11
```

When trying to run the console tool I'm using this command (sanitized):
```
.\CppSharp.CLI.exe -I=C:\foo\include\ -L=C:\foo\lib\ -l=bar.so -g=csharp -p=linux -a=x86 bar.h
```

**Comment by realvictorprm** [comment] 2017-08-09 06:26
Most obvious issue here is that an error is thrown due to loadIng assemblies which are incompatible with the architecture of the program.

**Comment by realvictorprm** [comment] 2017-08-09 06:28
Building the project on your own works like this:

1. Go into the build dir and run the DownloadDeps.bat

2. Run the Generate projects.bat 
3. Select your preferred vs version
4. Go into the generated folder and open the solution file.
5. Build

**Comment by kentcb** [comment] 2017-08-11 00:17
> Most obvious issue here is that an error is thrown due to loadIng assemblies which are incompatible with the architecture of the program.

Sure, but _why_? I was running on x64 Windows and installed the NuGet dependency. Is this not a supported means of using the tool?

I'm still confused over whether I can run this on an x64 Windows machine to generate bindings for x86 linux. Can you confirm?

**Comment by ddobrev** [comment] 2017-08-11 00:23
Our NuGet package is indeed 64-bit but I have just confirmed the packed version of the CLI tool is 32-bit (AnyCPU with "Prefer 32-bit" checked to be precise). Thank you for reporting this issue. We have been preparing for a new release and this bug will be fixed there. Meanwhile you could write your own small generator similar to our own tests. Basically - yes, you can generate Linux bindings on a x64 Windows. You could check the generator for our parser bindings as it generates Linux versions too.

**Comment by realvictorprm** [comment] 2017-08-11 06:06
Hey @kentcb, the Tool you're using is still new so the former approach was (and still is) to create a new console project which references CppSharp to create an own generator. Like @ddobrev Said, have a look into the test to get the grasp of how it works

**Comment by tritao** [comment] 2017-08-11 10:55
@kentcb Check here how to setup for Linux cross generation:

https://github.com/mono/CppSharp/blob/master/src/CLI/Generator.cs#L163
https://github.com/mono/CppSharp/blob/master/src/CLI/Generator.cs#L106

**Comment by tritao** [comment] 2017-08-28 00:32
Hey @kentcb, I sent some fixes for the CLI tool that might fix some of the issues you've faced.

If you could try the master version again it would be nice! If the issue persists, then I'd like to help get them fixed until the CLI works as expected.

**Comment by raidsan** [comment] 2018-02-05 05:57
I have build the vs2017 projectc successful,  but what's next step?     Generating bindings?  write interface ILibrary, but how to run it in  command?

**Comment by BaoBaoJiu** [comment] 2018-06-30 10:04
make sure platform target is x64

**Closed** 2019-01-04 12:40 UTC
