### ISSUE TITLE
Improving delegate generation

### ISSUE THREAD

**Issue by realvictorprm** [mono/CppSharp#800] opened 2017-03-23 13:55 UTC
##### Brief Description
The generated delegates are often not well to use and should be improved for the developer.
Instead of having a raw delegate for the developer a nicier, _high level_ one is prefered.

##### State:
I already talked with @ddobrev and @tritao about it and started implementing.
The new generated code should look like this:

```
public delegate void HighLevelDelegate (SomeClass class, int someparam);
internal delegate void LowLevelDelegate(IntPtr class, int someparam);

public void SetCallback(HighLevelDelegate del);
internal void SetCallback(LowLevelDelegate del);
```

However our current approach includes that each callback will be saved until the life-time of a specific class or the application itself ends.

**Comment by ddobrev** [comment] 2017-03-23 14:23
Duplicate of https://github.com/mono/CppSharp/issues/511 .

**Closed by ddobrev** 2017-03-23 14:23 UTC
