### ISSUE TITLE
Incompilable code when nesting more than one anonymous type

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#342] opened 2014-10-15 11:52 UTC
To reproduce, add one more anonymous type to TestNestedTypes in Basic.h and regenerate.

**Comment by genuinelucifer** [comment] 2015-05-13 11:14
I was trying to recreate this issue.. But,
I could NOT find any "TestEmptyName" in either of the 2 Basic.h files!! Am i missing something here?

**Comment by ddobrev** [comment] 2015-05-13 11:43
@genuinelucifer The type has been renamed to "TestNestedTypes" but the text of the issue hadn't. Sorry about that.

**Comment by genuinelucifer** [comment] 2015-05-13 12:43
Thanks. Can you please guide me where is the code for marshalling nested types so that I can work upon this.

**Comment by ddobrev** [comment] 2015-05-13 12:56
@genuinelucifer I assume you've reproduced the issue. You can start from the Generate* methods in CSharpTextTemplate: GenerateClass, GenerateMethod, etc.

**Comment by genuinelucifer** [comment] 2015-05-13 13:13
Yes, i reproduced the issue. Thanks, i will start working on it.

**Comment by genuinelucifer** [comment] 2015-05-14 03:38
@ddobrev @tritao Here is the diff file for the changes i made :
https://gist.github.com/genuinelucifer/08891fb6931cd63288e0
.
The code is fully compilable now and as you can see i nested 4 more anonymous types to test and it worked pretty well! 
The only thing I am concerned about is you may not find this solution elegant because one of the identifiers that was generated in Basic.cs had 33 underscores....
Please check and If this solution is acceptable, i will submit a pull request!

**Comment by genuinelucifer** [comment] 2015-06-16 03:48
Fixed by #451 . Please CLose this issue. @tritao @ddobrev

**Closed** 2015-06-16 22:15 UTC
