### ISSUE TITLE
MSVC 2017, nuget, NullReferenceException

### ISSUE THREAD

**Issue by adahn** [mono/CppSharp#922] opened 2017-08-24 14:52 UTC
##### Brief Description
I'm using CppSharp from NuGet (0.8.13) and have only Visual Studio in version 2017, which seems to be supported by CppSharp.

I've created generator executable with Library class, just like GettingStarted.md suggests. When I run it, I get NullReferenceException (see the stack trace).

After source code investigation, it seems to me, that the cause is `CppSharp.Parser.BuildConfig.Choice`, which is set to "vs2015" in NuGet build.

Is it possible to use CppSharp in vs2017? How can I override `CppSharp.Parser.BuildConfig.Choice`?

BTW, more informative error messages would be much, much appreciated.

OS: Windows 
Target: MSVC

##### Stack trace or incompilable generated code
```
   at CppSharp.MSVCToolchain.GetSystemIncludes(VisualStudioVersion vsVersion)
   at CppSharp.Parser.ParserOptions.SetupMSVC(VisualStudioVersion vsVersion)
   at CppSharp.Parser.ParserOptions.SetupMSVC()
   at CppSharp.Parser.ParserOptions.SetupIncludes()
   at CppSharp.Driver.Setup()
   at CppSharp.ConsoleDriver.Run(ILibrary library)
   at Generator.Generator.Main() in D:\projects\traffic\c_api\dotnet\traffic\Generator.cs:line 46
```

**Comment by ddobrev** [comment] 2017-08-24 15:44
Hello @adahn . Thank you for your report. What you've discovered is actually a bug because our code is supposed to use any VS it can find as a fallback. It's not normal for it to crash. May I ask you to build C++# from source, configure it for VS 2015 and debug to see why we crash?

**Comment by tritao** [comment] 2017-08-24 15:53
The issue is that we're expecting the `BuildConfig` VS to exist, which might not be true with builds distributed to users.

@ddobrev We need to change this code: https://github.com/mono/CppSharp/blob/27efa2ec871eb79a02c8d3c6ae09287317e8d99a/src/Parser/ParserOptions.cs#L46

To something like:

```
// Try the VS used to build CppSharp
try {
    SetupMSVC(vsVersion);
    return;
} catch (Exception ex) {
}

// Try the latest VS.
SetupMSVC(VisualStudioVersion.Latest);
```

**Comment by tritao** [comment] 2017-08-24 15:55
@adahn As a workaround for now, you can try:

```
options.NoBuiltinIncludes = true;
```

And then setup MSVC manually:

```
parserOptions.SetupMSVC(VisualStudioVersion.VS2017);
```

**Comment by adahn** [comment] 2017-08-25 10:12
The workaround helped. Thanks a lot!

But there is another problem. Now, CppSharp hangs with a following log:
```
Parsing libraries...
Parsing code...
ignoring nonexistent directory "D:\Program Files\Microsoft Visual Studio\2017\VC\Tools\MSVC\14.10.25017\atlmfc\include"
#include "..." search starts here:
#include <...> search starts here:
 D:\projects\traffic\c_api\dotnet\traffic\bin\Debug\lib\clang\5.0.0\include
 D:\Program Files\Microsoft Visual Studio\2017\VC\Tools\MSVC\14.10.25017\include
 C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared
 C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um
 C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt
 C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt
End of search list.
Processing code...
Pass 'CppSharp.Passes.SortDeclarationsPass'
Pass 'CppSharp.Passes.ResolveIncompleteDeclsPass'
Pass 'CppSharp.Passes.IgnoreSystemDeclarationsPass'
Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
Pass 'CppSharp.Passes.GenerateSymbolsPass'
Pass 'CppSharp.Passes.TrimSpecializationsPass'
Pass 'CppSharp.Passes.FindSymbolsPass'
```

Debug break shows following callstack:
```
 	mscorlib.dll!System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle waitableSafeHandle, long millisecondsTimeout, bool hasThreadAffinity, bool exitContext)	Unknown
 	mscorlib.dll!System.Threading.WaitHandle.WaitOne(int millisecondsTimeout, bool exitContext)	Unknown
 	CppSharp.Generator.dll!CppSharp.Passes.FindSymbolsPass.VisitASTContext(CppSharp.AST.ASTContext context)	Unknown
 	CppSharp.Generator.dll!CppSharp.Generators.BindingContext.RunPasses.AnonymousMethod__37_0(CppSharp.Passes.TranslationUnitPass pass)	Unknown
 	CppSharp.Generator.dll!CppSharp.PassBuilder<CppSharp.Passes.TranslationUnitPass>.RunPasses(System.Action<CppSharp.Passes.TranslationUnitPass> action)	Unknown
 	CppSharp.Generator.dll!CppSharp.Generators.BindingContext.RunPasses()	Unknown
 	CppSharp.Generator.dll!CppSharp.Driver.ProcessCode()	Unknown
 	CppSharp.Generator.dll!CppSharp.ConsoleDriver.Run(CppSharp.ILibrary library)	Unknown
>	Generator.exe!Generator.Generator.Main() Line 53	C#
```

It doesn't matter what includes or libs I am providing. In fact, I can leave ILibrary::Setup function empty (except for manual MSVC setup, as shown by @tritao) and the result is the same.

Version is the same: NuGet 0.8.13 with VS2017.

**Comment by ddobrev** [comment] 2017-08-25 10:16
@adahn this is a known bug which has already been fixed in master. We are aiming for a release in the next few days which is going to have the fix included.

**Comment by adahn** [comment] 2017-08-25 10:26
That's great! Thanks again!

**Closed** 2017-08-27 08:55 UTC
