### ISSUE TITLE
The OS X build crashes if the destructor of CppSharp::CppParser::AST::Comment is virtual

### ISSUE THREAD

**Issue by ddobrev** [mono/CppSharp#599] opened 2015-12-23 01:42 UTC
CppSharp::CppParser::AST::Comment used to have a virtual destructor as a cleaner solution to the proper memory management. However, it crashed the OS X build: https://travis-ci.org/mono/CppSharp/jobs/98438635. It does not occur with either the C++/CLI or the C# binding on Windows.
 The inferior solution used now - https://github.com/mono/CppSharp/commit/a95511600fd0d23997c6291c6df63343b0a9b59b - does not crash the build so it's preferable for the time being.
This is most probably the same type of bug as https://github.com/mono/CppSharp/issues/598.

**Comment by tritao** [comment] 2015-12-27 13:13
Duplicate of #598

**Closed by tritao** 2015-12-27 13:13 UTC
