### ISSUE TITLE
AccessViolationException when parsing the Autodesk FBX SDK header

### ISSUE THREAD

**Issue by Frooxius** [mono/CppSharp#1111] opened 2018-08-02 00:36 UTC
##### Brief Description
Hello. I am trying to generate C# (P/Invoke) bindings for the Autodesk FBX SDK, however running the generation throws a System.AccessViolationException exception during the "Parsing code" step with message "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

I've used the latest CppSharp NuGet package (0.8.21) with Visual Studio 2017 Community.

OS: Windows 10 Pro (Version 1803, Build 17134.165)

##### Used headers
fbxsdk.h from the Autodesk FBX SDK 2019.0 VS2015 (Free download here: https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2019-0 )

I've replicated the same issue with SDK versions 2018.1.1, 2018.0, 2017.0.1, 2016.1 and 2015.1.

##### Used settings
I've used code based on the "Generating Bindings" example with the following setup snippet (everything else is default/empty).

rootPath is set to: @"C:\Program Files\Autodesk\FBX\FBX SDK\2019.0" for my test.

```
public void Setup(Driver driver)
        {
            var options = driver.Options;
            options.GeneratorKind = GeneratorKind.CSharp;
            options.Verbose = true;

            var module = options.AddModule("FBXSDK");
            module.IncludeDirs.Add(Path.Combine(rootPath, "include"));
            module.Headers.Add("fbxsdk.h");
            module.LibraryDirs.Add(Path.Combine(rootPath, @"lib\vs2015\x64\release"));
            module.Libraries.Add("libfbxsdk.dll");
        }
```

Here is the full project if you need it (need to install the FBX SDK 2019.0 separately though): https://cp.sync.com/dl/bb2a46060#s2azfzty-d5kenihj-tase8gf2-if7f3ds7

##### Stack trace or incompilable generated code

```
   at CppSharp.CppParser.ClangParser.ParseHeader(CppParserOptions* )
   at CppSharp.Parser.ClangParser.ParseHeader(CppParserOptions Opts)
   at CppSharp.ClangParser.ParseSourceFiles(IEnumerable`1 files, ParserOptions options)
   at CppSharp.ClangParser.ParseSourceFile(String file, ParserOptions options)
   at CppSharp.Driver.ParseCode()
   at CppSharp.ConsoleDriver.Run(ILibrary library)
   at AutodeskFBXSharpGenerator.Program.Main(String[] args) in D:\Sync\Projects\Software\Applications\NeoS\Dependencies\AutodeskFBXSharpGenerator\AutodeskFBXSharpGenerator\Program.cs:line 15
```

**Comment by tritao** [comment] 2018-08-02 09:00
This is probably a mis-use of something in the Clang parsing code.

It needs to be debugged under debug mode and enabling mixed mode unmanaged debugging in VS.

**Comment by Frooxius** [comment] 2018-09-12 20:38
Hello. I have done some more investigation, but this issue is proving to be a bit difficult to reduce to a simple case.

It seems to be related to template classes and typedefs. In fbxpropertypage.h file, I have found these lines:

`typedef FbxMap<FbxNameMapKey, FbxInt, FbxNameMapCompare > NameMap;
typedef FbxPair<unsigned int, NameMap > NameLookupPair;
NameLookupPair     mNameMap;`

Running the CppSharp on only this header file in its original state causes the Access Violation. However if I replace it with explicit type definition like so:

```FbxPair<unsigned int, FbxMap<FbxNameMapKey, FbxInt, FbxNameMapCompare > >     mNameMap;```

The file parses correctly, without changing anything else.

However I'm having trouble isolating this, when I start reducing the template classes, the issue just goes away at some point. Do you have any clue what it might be or how to better isolate this?

**Comment by ddobrev** [comment] 2018-09-19 00:12
Would there be any chance to include both headers and then start reducing them until you come up with an isolated case?

**Comment by Frooxius** [comment] 2018-09-26 00:11
I have attempted to isolate it to a small case, but it's proving very difficult, because the thing is a tangled mess of templates within templates and lots of inter-dependencies, so either I'd get lots of compilation errors or the issue would go away and it would compile fine.

I'm not really sure what to look for when trying to isolate the issue and random isolation is unfortunately too time costly for me.

**Comment by tritao** [comment] 2018-09-26 00:35
Send us whatever you have that can repro the issue.

**Comment by tritao** [comment] 2018-11-06 16:48
Probably another dupe of https://github.com/mono/CppSharp/issues/1123 / https://github.com/mono/CppSharp/issues/1124.

**Comment by tritao** [comment] 2018-11-06 18:29
Can you check again with master?

**Closed** 2018-12-07 16:02 UTC
