### ISSUE TITLE
Binding generation issue

### ISSUE THREAD

**Issue by benpye** [mono/CppSharp#432] opened 2015-03-23 19:19 UTC
I've been revisiting CppSharp in the hope that I'd be able to programatically generate bindings for libspotify. I have been able to compile the project, and it does run, however I am hitting a bit of a wall when it comes to actually setting up the library for use. libspotify relies on typedefs for opaque types, which appears to cause issues with CppSharp.

```
typedef struct sp_session sp_session; ///< Representation of a session
typedef struct sp_track sp_track; ///< A track handle
typedef struct sp_album sp_album; ///< An album handle
typedef struct sp_artist sp_artist; ///< An artist handle
typedef struct sp_artistbrowse sp_artistbrowse; ///< A handle to an artist browse result
typedef struct sp_albumbrowse sp_albumbrowse; ///< A handle to an album browse result
typedef struct sp_toplistbrowse sp_toplistbrowse; ///< A handle to a toplist browse result
typedef struct sp_search sp_search; ///< A handle to a search result
typedef struct sp_link sp_link; ///< A handle to the libspotify internal representation of a URI
typedef struct sp_image sp_image; ///< A handle to an image
typedef struct sp_user sp_user; ///< A handle to a user
typedef struct sp_playlist sp_playlist; ///< A playlist handle
typedef struct sp_playlistcontainer sp_playlistcontainer; ///< A playlist container (playlist containing other playlists) handle
typedef struct sp_inbox sp_inbox; ///< Add to inbox request handle
```

Above shows how the typedefs are written, this causes CppSharp to give the following errors (many more in practice, however all to the same effect).

```
Parsing libraries...
Parsed 'libspotify.lib'
Indexing library symbols...
Parsing code...
#include "..." search starts here:
#include <...> search starts here:
 ../../../libspotify/include/libspotify
 .\lib\clang\3.7.0\include
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
 C:\Program Files (x86)\Windows Kits\8.1\\include
End of search list.
Parsed 'api.h'
#include "..." search starts here:
#include <...> search starts here:
 ../../../libspotify/include/libspotify
 .\lib\clang\3.7.0\include
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
 C:\Program Files (x86)\Windows Kits\8.1\\include
End of search list.
Processing code...
Pass 'CppSharp.Passes.CleanUnitPass'
Pass 'CppSharp.Passes.SortDeclarationsPass'
Pass 'CppSharp.Passes.ResolveIncompleteDeclsPass'
    Unresolved declaration: sp_session
    Unresolved declaration: sp_track
...
Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Function 'sp_session_create' was ignored due to incomplete param
    Function 'sp_session_user' was ignored due to incomplete return decl
    Typedef 'sp_session' was ignored due to incomplete type
    Typedef 'sp_track' was ignored due to incomplete type
    Typedef 'sp_album' was ignored due to incomplete type
...
Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Property 'logged_in' was ignored due to ignored decl
    Function 'sp_session_playlistcontainer' was ignored due to incomplete return decl
Pass 'CppSharp.Passes.CheckFlagEnumsPass'
Pass 'CppSharp.Passes.CheckDuplicatedNamesPass'
Pass 'CppSharp.Passes.RenameRootNamespacesPass'
Generating code...
Generated 'api.cs'
```

The full log can be found at https://gist.github.com/benpye/b05437bfda34acf6494e . Sorry if this is an inappropriate place to ask about this, however documentation seems very light on the ground at this point.

**Comment by txdv** [comment] 2015-03-23 19:45
I'm not dis-encouraging you to create bindings for libspotify, but you might be interested in this: https://github.com/torshy/torshify

**Comment by benpye** [comment] 2015-03-23 21:39
Thanks, I will probably use that however, I am still interested in how I am misusing CppSharp. Up until now I hadn't found anything other than SpotiFire which is Windows only.

**Comment by tritao** [comment] 2015-03-31 11:53
As you've found out our support for C is not very robust so it doesn't surprise me that we need a few tweaks here and there to make it work with the idioms in that language. This seems one of those cases. 

We already have an `IsOpaque` property that can be used to signal this: https://github.com/mono/CppSharp/blob/d2d941638a87656c429121ef99ccc023b3dce2e7/src/AST/Class.cs#L84

You can try to set that on your types, like the outdated Clang sample does: https://github.com/mono/CppSharp/blob/10d9384ccace01fc46aa395f0a82db2ae279015e/examples/Clang/Clang.cs#L18

Though it's quite possible that the generator itself or the passes that check for ignored types need some work to let those opaque types through.

**Comment by benpye** [comment] 2015-04-02 13:22
Yeah I did try setting IsOpaque, both by finding the class and the helper method, neither worked unfortunately. I believe what you said about the later passes needing to allow opaque types is true.

**Comment by txdv** [comment] 2015-04-03 04:33
I wonder what your advice is on handling types that are not really declared, as in, their layout is not declared but the type is used as a pointer in a bunch of methods.

Currently CppSharp just ignores them as being incomplete and doesn't generate bindings for any method containing an argument or return type with that contain such an incomplete type.

**Comment by jasper22** [comment] 2015-06-03 13:50
May be I'm doing something wrong by current version of CppSharp can not read typedef definitions from another .h file :( I have to manually copy all my 'typedef' lines to every (!) file where it's used :(

**Comment by tritao** [comment] 2015-06-03 14:10
Could you create another issue and post some more details about your problem? You definitely should not need to manually copy typedefs, the parsing is handled by Clang.

**Comment by jasper22** [comment] 2015-06-03 16:54
Hi @tritao - this is gist: https://gist.github.com/jasper22/f90d7594045a24e1ac30

but may be I did something wrong :(  

P.S. If you need libELF it's here: https://github.com/jasper22/libELF

**Comment by tritao** [comment] 2015-06-03 17:48
From quick glance, I think the problem is that you're trying to pass all libDWARF headers to CppSharp, I suspect some of them are not meant to be included on their own but only as part of other files. For instance, `dwarf_abbrev.h` does not include any other files, even though it uses types that are defined outside its translation unit.

The same will happen if you try to use those errors with a C++ compiler.

**Comment by benpye** [comment] 2016-03-01 10:38
This is annoyingly still an issue, it also affects the SDL example. Any new ideas on how to get around this?

**Comment by tritao** [comment] 2016-03-01 11:10
Hi @benpye, I will look into fixing the issue.

**Comment by tritao** [comment] 2017-12-04 11:17
I believe this should be fixed.

**Closed by tritao** 2017-12-04 11:17 UTC
