### ISSUE TITLE
The return value CppSignatureType() does not get processed properly. 

### ISSUE THREAD

**Issue by polar** [mono/CppSharp#1357] opened 2020-04-23 00:26 UTC
##### Brief Description

I have a class of which I want to write my own marshalling rules. Before 27-02-2020, I was able to get this working nicely by adding a `[TypeMap("A", GeneratorKind.CSharp)]` to a supertype of the TypeMap class of my own design.

Let's call the interface `A`, and it is defined as such:
```
struct A { A(); }
struct B { B(); }
```
This definition would automatically generate the following definition for `operator=` in the `symbols.cpp` file.
```
A& (A::*_0)(const A&&) = &A::operator=;
A& (A::*_1)(A&&) = &A::operator=;
B& (B::*_2)(const B&&) = &B::operator=;
B& (B::*_3)(B&&) = &B::operator=;
```
However, after merging my branch with the current master, I now end up with:
```
void* (A:*_0)(void*) = &A::operator=;
void* (A:*_1)(void*) = &A::operator=;
B& (B::*_2)(const B&&) = &B::operator=;
B& (B::*_3)(B&&) = &B::operator=;
```
which is clearly wrong. What happened? After looking around the visit pattern in the CppTypePrinter, and I added the following definition to `A`'s TypeMap:
```
public override Type CppSignatureType(TypePrinterContext ctx)
{
    return new CustomType("A");
}
```
However, it did not generate the correct definition:
```
A (A::*_0)(A) = &A::operator=;
A (A::*_1)(A) = &A::operator=;
B& (B::*_2)(const B&&) = &B::operator=;
B& (B::*_3)(B&&) = &B::operator=;
```

What's changed? Before, I did NOT need to define CppSignatureType(), and it looks like it would get a default for the class, which is annotated correctly. 

It does not appear that I can rectify this issue solely from TypeMap.  It seems that the CppTypePrinter that consumes this item is not putting the proper qualifiers `&` and `const &&` on it.

OS: Windows / OS X / Linux (include version and/or distro)
Linux for now

**Comment by tritao** [comment] 2020-04-23 00:49
We added some more accurate type map checking to `CppTypePrinter` lately, that's why this started breaking for you.

I think the right fix here should be to ignore all type maps when generating native type names for the symbols. Since it's trying to generate names matching the original symbols, then we should never want type maps to apply in that context. What do you think @ddobrev?

What happens if you do `return base. CppSignatureType()` instead of returning a `CustomType`? Does that still break?

**Comment by ddobrev** [comment] 2020-04-23 10:52
@tritao the _conversion_ of `A&` to `void*` reminds me of that recent regression of ours. It's reproducible each time we generate our parser bindings, the difference can be seen in `Std-symbols.cpp`. I'll see if I can fix it by the end of the week.

**Comment by polar** [comment] 2020-04-23 13:59
@tritao I did not have CppSignatureType defined before, so I believe returning `base.CppSignatureType(ctx)` would not alter the original result. Anyway, I have just confirmed that we end up with the original issue, producing `void*`.

**Comment by ddobrev** [comment] 2020-04-28 00:34
Fixed by https://github.com/mono/CppSharp/commit/d0216f1e7d506a7d639e5288da78229ef72cde9d.

**Closed by ddobrev** 2020-04-28 00:34 UTC
