### ISSUE TITLE
Can't control name mangling

### ISSUE THREAD

**Issue by TechnikEmpire** [mono/CppSharp#641] opened 2016-04-08 11:43 UTC
Forgive me if I've missed this in the docs somewhere.

I'm trying to control the name mangling on extern function definitions. I'm trying to generate pinvoke code for part of the Win API. I tried:
```
public void Setup(Driver driver)
{ 
    var options = driver.Options;
    options.LanguageVersion = CppSharp.Parser.LanguageVersion.C;
}
```
But this instead just causes a crash with:

```
error: invalid argument '-std=gnu99' not allowed with 'C++/ObjC++'
Unhandled type class 'FunctionNoProto'

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CppSharp.CppParser.ClangParser.ParseHeader(ParserOptions* )
   at CppSharp.Parser.ClangParser.ParseHeader(ParserOptions Opts) in c:\projects\cppsharp\src\cppparser\bindings\cli\cppparser.cpp:line 531
   at CppSharp.ClangParser.ParseSourceFile(SourceFile file) in C:\projects\cppsharp\src\Core\Parser\Parser.cs:line 59
   at CppSharp.ClangParser.<ParseProject>b__10_0(SourceFile s) in C:\projects\cppsharp\src\Core\Parser\Parser.cs:line 73
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CppSharp.ClangParser.ParseProject(Project project) in C:\projects\cppsharp\src\Core\Parser\Parser.cs:line 73
   at CppSharp.Driver.ParseCode() in C:\projects\cppsharp\src\Generator\Driver.cs:line 205
   at CppSharp.ConsoleDriver.Run(ILibrary library) in C:\projects\cppsharp\src\Generator\Driver.cs:line 475
```

I'm assuming I am handling this incorrectly. The libraries I'm trying to generate code for only have exported C functions (obviously no mangling) but no matter what I do, or what I override using my own `TranslationUnitPass`, I cannot modify this successfully. I always get mangled names in the `DllImportAttribute::EntryPoint` member. So I guess this is two questions: 

1) Is this the correct way to do this, making this a bug?
2) Where/how can I override generation of attributes such as `DllImportAttribute`?

Thanks in advance and thanks for publishing this tool its brilliant.

**Comment by tritao** [comment] 2016-04-08 11:58
`LanguageVersion.C` is used to tell the compiler to parse the code in C mode, but given the error you posted, `error: invalid argument '-std=gnu99' not allowed with 'C++/ObjC++'` it looks like your sources are C++ files (and named `.cpp`, is that the case?). If your sources are C files (named `.c`) then we might have a bug.

If I understood correctly, the issue is that you want the name mangling of certain functions to be in plain C. If your sources are C++, that is usually done by wrapping those functions in an `extern "C" {}` block.

About DllImport, it is handled in https://github.com/mono/CppSharp/blob/11fc1f5097f14e5ca50bebf333a46c7c6bf4c30e/src/Generator/Generators/CSharp/CSharpTextTemplate.cs#L3004. We have no easy way of overriding, why do you need it?

**Comment by TechnikEmpire** [comment] 2016-04-08 12:10
Perhaps I'm using this tool beyond its intended scope. I'm only supplying headers, and they're definitely C headers. With regard to overriding the attribute, it's because the functions I'm pinvoking against are C exports, no mangling, so the `::EntryPoint` definitions generated on all the `extern` definitions are incorrect. It's not a big deal though, I can write a regex in notepad++ to demangle manually. Everything else is great. :)

**Comment by tritao** [comment] 2016-04-08 12:15
Well if the headers are C code, then CppSharp should work out of the box. There should be no need to manually change the generated output, I consider that a bug.

Can you share the input code that gives out the exception above in C language mode?

**Comment by TechnikEmpire** [comment] 2016-04-08 15:03
Input code? I created a basic example wrapping some of the headers for the Windows Filtering Platform and it's treating it all as C++. Nothing more than what the walkthrough tutorial code shows.

**Comment by tritao** [comment] 2016-04-08 15:34
Pushed a fix for the error, turns out to be a pretty silly issue.

**Comment by TechnikEmpire** [comment] 2016-04-08 15:44
Haha that's usually the way it is isn't it? Thanks man, AAA support for any product, especially a free one. :)

**Comment by tritao** [comment] 2016-04-08 15:59
That only fixes the first issue though, looks like there's another one dealing with FunctionNoProto types, which will also need a fix.

**Closed** 2016-04-08 16:08 UTC
